export const TASKS_ADD_TASK_START = "TASKS_ADD_TASK_START";
export const TASKS_ADD_TASK_SUCCESS = "TASKS_ADD_TASK_SUCCESS";
export const TASKS_ADD_TASK_FAIL = "TASKS_ADD_TASK_FAILURE";

export const TASKS_GET_TASKS_START = "TASKS_GET_TASKS_START";
export const TASKS_GET_TASKS_SUCCESS = "TASKS_GET_TASKS_SUCCESS";
export const TASKS_GET_TASKS_FAIL = "TASKS_GET_TASKS_FAILURE";
export const TASKS_SET_TASKS = "TASKS_SET_TASKS";

export const TASKS_UPDATE_TASK_START = "TASKS_UPDATE_TASK_START";
export const TASKS_UPDATE_TASK_SUCCESS = "TASKS_UPDATE_TASK_SUCCESS";
export const TASKS_UPDATE_TASK_FAIL = "TASKS_UPDATE_TASK_FAILURE";
export const TASKS_UPDATE_TASKS = "TASKS_UPDATE_TASKS";

export const TASKS_DEL_TASK_START = "TASKS_DEL_TASK_START";
export const TASKS_DEL_TASK_SUCCESS = "TASKS_DEL_TASK_SUCCESS";
export const TASKS_DEL_TASK_FAIL = "TASKS_DEL_TASK_FAILURE";

