export const COMMANDS_RUN_COMMAND_START = "COMMANDS_RUN_COMMAND_START";
export const COMMANDS_RUN_COMMAND_SUCCESS = "COMMANDS_RUN_COMMAND_SUCCESS";
export const COMMANDS_RUN_COMMAND_FAIL = "COMMANDS_RUN_COMMAND_FAILURE";
export const COMMANDS_RUN_COMMAND = "COMMANDS_RUN_COMMAND";


